// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-OPh4q1vaNoeSlUrcfR07Rz5mf7DkKUw',
    appId: '1:813450648626:web:31be975b756593070c302b',
    messagingSenderId: '813450648626',
    projectId: 'adwaes-f79d8',
    authDomain: 'adwaes-f79d8.firebaseapp.com',
    storageBucket: 'adwaes-f79d8.appspot.com',
    measurementId: 'G-SL96J3HJX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwyorGmq_dqLJlKit2fH7rZ_7aGn7DbCw',
    appId: '1:813450648626:android:434322df99577b4e0c302b',
    messagingSenderId: '813450648626',
    projectId: 'adwaes-f79d8',
    storageBucket: 'adwaes-f79d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR5PUihuL4nwZ_QdX7cNqCngBoHCv1Nkk',
    appId: '1:813450648626:ios:2e9094974217c1b00c302b',
    messagingSenderId: '813450648626',
    projectId: 'adwaes-f79d8',
    storageBucket: 'adwaes-f79d8.appspot.com',
    iosClientId: '813450648626-9c51jtl1vbnatdb5u777hdibh99ju78n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR5PUihuL4nwZ_QdX7cNqCngBoHCv1Nkk',
    appId: '1:813450648626:ios:2e9094974217c1b00c302b',
    messagingSenderId: '813450648626',
    projectId: 'adwaes-f79d8',
    storageBucket: 'adwaes-f79d8.appspot.com',
    iosClientId: '813450648626-9c51jtl1vbnatdb5u777hdibh99ju78n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ad',
  );
}
